
spring:
  application:
    name: community-service

server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG

webclient.h2-console-port: 8081

